<?php

namespace AppBundle\Repository;

/**
 * HistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricoRepository extends \Doctrine\ORM\EntityRepository
{
}
