<?php

namespace AppBundle\Repository;

/**
 * NodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodoRepository extends \Doctrine\ORM\EntityRepository
{
}
