<?php

namespace AppBundle\Repository;

/**
 * SensorInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
