<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJc21xyo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJc21xyo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJc21xyo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJc21xyo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJc21xyo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jc21xyo',
    'container.build_id' => '356bf83e',
    'container.build_time' => 1551335658,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJc21xyo');
