<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVzlgvlj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVzlgvlj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVzlgvlj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVzlgvlj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVzlgvlj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vzlgvlj',
    'container.build_id' => 'c2cac6a3',
    'container.build_time' => 1551333251,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVzlgvlj');
